### ISSUE TITLE
Dataset y Reader

### ISSUE THREAD

**Issue by JAntonioVR** [JAntonioVR/IV-2021-2022#23]
Necesito un dataset de reseñas de restaurantes y una forma de leerlo para poder hacer los tests.

Este issue referencia a la HU0: Extracción de aspectos positivos y negativos (#12)

**Comment by JAntonioVR** [comment]
Este issue referencia a la HU0: Extracción de aspectos positivos y negativos (#12)

**Comment by JJ** [comment]
Enlaza las HU directamente en el cuerpo del issue, no en un comentario.
