### ISSUE TITLE
Comprobación de instancias

### ISSUE THREAD

**Issue by JAntonioVR** [JAntonioVR/IV-2021-2022#28]
Necesito test que comprueben que las instancias están bien definidas:
* El constructor de `ConjuntoResenias` no puede devolver `None`
* Si cargo los datos a partir de un fichero ese fichero tiene que existir
* `ConjuntoResenias` debe tener un array de objetos de la clase `Resenia`
* Cada objeto de la clase `Resenia` debe tener un texto no vacío, una puntuación entera entre 1 y 5 y un identificador del local reseñado, también no vacío.

**Comment by JAntonioVR** [comment]
Test implementados :clap:

**Comment by JAntonioVR** [comment]
Este issue referencia a la HU0: Extracción de aspectos positivos y negativos (#12)

**Comment by JJ** [comment]
Si no explicas en el cuerpo del issue qué son "instancias" ni a qué HU se refiere, es imposible saber qué hay que hacer.
